openapi: 3.1.0
info:
  title: My Bookshop
  version: '1.0'
paths:
  /hello:
    get:
      operationId: getHello
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 'Invalid value for: query parameter name'
          content:
            text/plain:
              schema:
                type: string
  /books/list/all:
    get:
      operationId: getBooksListAll
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Author:
      title: Author
      type: object
      required:
      - name
      properties:
        name:
          type: string
    Book:
      title: Book
      type: object
      required:
      - title
      - year
      - author
      properties:
        title:
          type: string
        year:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/Author'
    User:
      title: User
      type: object
      required:
      - name
      properties:
        name:
          type: string
